export const barangays = {
  poblacion: [
    { key: "1-a", value: "1-A", district: 1 },
    { key: "2-a", value: "2-A", district: 1 },
    { key: "3-a", value: "3-A", district: 1 },
    { key: "4-a", value: "4-A", district: 1 },
    { key: "5-a", value: "5-A", district: 1 },
    { key: "6-a", value: "6-A", district: 1 },
    { key: "7-a", value: "7-A", district: 1 },
    { key: "8-a", value: "8-A", district: 1 },
    { key: "9-a", value: "9-A", district: 1 },
    { key: "10-a", value: "10-A", district: 1 },
    { key: "11-b", value: "11-B", district: 1 },
    { key: "12-b", value: "12-B", district: 1 },
    { key: "13-b", value: "13-B", district: 1 },
    { key: "14-b", value: "14-B", district: 1 },
    { key: "15-b", value: "15-B", district: 1 },
    { key: "16-b", value: "16-B", district: 1 },
    { key: "17-b", value: "17-B", district: 1 },
    { key: "18-b", value: "18-B", district: 1 },
    { key: "19-b", value: "19-B", district: 1 },
    { key: "20-b", value: "20-B", district: 1 },
    { key: "21-c", value: "21-C", district: 1 },
    { key: "22-c", value: "22-C", district: 1 },
    { key: "23-c", value: "23-C", district: 1 },
    { key: "24-c", value: "24-C", district: 1 },
    { key: "25-c", value: "25-C", district: 1 },
    { key: "26-c", value: "26-C", district: 1 },
    { key: "27-c", value: "27-C", district: 1 },
    { key: "28-c", value: "28-C", district: 1 },
    { key: "29-c", value: "29-C", district: 1 },
    { key: "30-c", value: "30-C", district: 1 },
    { key: "31-d", value: "31-D", district: 1 },
    { key: "32-d", value: "32-D", district: 1 },
    { key: "33-d", value: "33-D", district: 1 },
    { key: "34-d", value: "34-D", district: 1 },
    { key: "35-d", value: "35-D", district: 1 },
    { key: "36-d", value: "36-D", district: 1 },
    { key: "37-d", value: "37-D", district: 1 },
    { key: "38-d", value: "38-D", district: 1 },
    { key: "39-d", value: "39-D", district: 1 },
    { key: "40-d", value: "40-D", district: 1 },
  ],
  talomo: [
    { key: "bago-aplaya", value: "Bago Aplaya", district: 1 },
    { key: "bago-gallera", value: "Bago Gallera", district: 1 },
    { key: "baliok", value: "Baliok", district: 1 },
    { key: "bucana", value: "Bucana", district: 1 },
    { key: "catalunan-grande", value: "Catalunan Grande", district: 1 },
    { key: "catalunan-pequeño", value: "Catalunan Pequeño", district: 1 },
    { key: "dumoy", value: "Dumoy", district: 1 },
    { key: "langub", value: "Langub", district: 1 },
    { key: "maa", value: "Maa", district: 1 },
    { key: "magtuod", value: "Magtuod", district: 1 },
    { key: "matina-aplaya", value: "Matina Aplaya", district: 1 },
    { key: "crossing", value: "Crossing", district: 1 },
    { key: "matina-pangi", value: "Matina Pangi", district: 1 },
    { key: "talomo", value: "Talomo Proper", district: 1 },
  ],
  agdao: [
    { key: "agdao-proper", value: "Agdao Proper", district: 2 },
    { key: "san-juan", value: "Centro (San Juan)", district: 2 },
    { key: "agdao-paciano", value: "Gov. Paciano Bangoy", district: 2 },
    { key: "kap-tomas", value: "Kap. Tomas Monteverde, Sr.", district: 2 },
    { key: "vicente-duterte", value: "Gov. Vicente Duterte", district: 2 },
    { key: "lapu-lapu", value: "Lapu-Lapu", district: 2 },
    { key: "leon-garcia", value: "Leon Garcia", district: 2 },
    { key: "rafael-castillo", value: "Rafael Castillo", district: 2 },
    { key: "san-antonio", value: "San Antonio", district: 2 },
    { key: "ubalde", value: "Ubalde", district: 2 },
    { key: "wilfredo-quirino", value: "Wilfredo Quirino", district: 2 },
  ],
  buhangin: [
    { key: "acacia", value: "Acacia", district: 2 },
    { key: "alfonso-angliongto", value: "Alfonso Angliongto", district: 2 },
    { key: "buhangin-proper", value: "Buhangin Proper", district: 2 },
    { key: "cabantian", value: "Cabantian", district: 2 },
    { key: "communal", value: "Communal", district: 2 },
    { key: "callawa", value: "Callawa", district: 2 },
    { key: "indangan", value: "Indangan", district: 2 },
    { key: "mandug", value: "Mandug", district: 2 },
    { key: "pampanga", value: "Pampanga", district: 2 },
    { key: "sasa", value: "Sasa", district: 2 },
    { key: "tigatto", value: "Tigatto", district: 2 },
    { key: "hizon", value: "Vicente Hizon Sr.", district: 2 },
    { key: "waan", value: "Waan", district: 2 },
  ],
  bunawan: [
    { key: "lasang", value: "Alejandro Navarro (Lasang)", district: 2 },
    { key: "bunawan-proper", value: "Bunawan Proper", district: 2 },
    { key: "gatungan", value: "Gatungan", district: 2 },
    { key: "ilang", value: "Ilang", district: 2 },
    { key: "mahayag", value: "Mahayag", district: 2 },
    { key: "mudiang", value: "Mudiang", district: 2 },
    { key: "panacan", value: "Panacan", district: 2 },
    { key: "licanan", value: "San Isidro (Licanan)", district: 2 },
    { key: "tibungco", value: "Tibungco", district: 2 },
  ],
  paquibato: [
    { key: "colosas", value: "Colosas", district: 2 },
    { key: "fatima-benowang", value: "Fatima (Benowang)", district: 2 },
    { key: "lumiad", value: "Lumiad", district: 2 },
    { key: "mabuhay", value: "Mabuhay", district: 2 },
    { key: "malabog", value: "Malabog", district: 2 },
    { key: "mapula", value: "Mapula", district: 2 },
    { key: "panalum", value: "Panalum", district: 2 },
    { key: "pandaitan", value: "Pandaitan", district: 2 },
    { key: "paquibato-proper", value: "Paquibato Proper", district: 2 },
    { key: "paradise-embak", value: "Paradise Embak", district: 2 },
    { key: "salapawan", value: "Salapawan", district: 2 },
    { key: "sumimao", value: "Sumimao", district: 2 },
    { key: "tapak", value: "Tapak", district: 2 },
  ],
  baguio: [
    { key: "baguio-proper", value: "Baguio Proper", district: 3 },
    { key: "cadalian", value: "Cadalian", district: 3 },
    { key: "carmen", value: "Carmen", district: 3 },
    { key: "gumalang", value: "Gumalang", district: 3 },
    { key: "malagos", value: "Malagos", district: 3 },
    { key: "tambubong", value: "Tambubong", district: 3 },
    { key: "tawan-tawan", value: "Tawan Tawan", district: 3 },
    { key: "wines", value: "Wines", district: 3 },
  ],
  calinan: [
    { key: "biao-joaquin", value: "Biao Joaquin", district: 3 },
    { key: "calinan-proper", value: "Calinan Proper", district: 3 },
    { key: "cawayan", value: "Cawayan", district: 3 },
    { key: "dacudao", value: "Dacudao", district: 3 },
    { key: "dalagdag", value: "Dalagdag", district: 3 },
    { key: "dominga", value: "Dominga", district: 3 },
    { key: "inayangan", value: "Inayangan", district: 3 },
    { key: "lacson", value: "Lacson", district: 3 },
    { key: "lamanan", value: "Lamanan", district: 3 },
    { key: "lampianao", value: "Lampianao", district: 3 },
    { key: "megkawayan", value: "Megkawayan", district: 3 },
    { key: "pangyan", value: "Pangyan", district: 3 },
    { key: "riverside", value: "Riverside", district: 3 },
    { key: "saloy", value: "Saloy", district: 3 },
    { key: "sirib", value: "Sirib", district: 3 },
    { key: "subasta", value: "Subasta", district: 3 },
    { key: "talomo-river", value: "Talomo River", district: 3 },
    { key: "tamayong", value: "Tamayong", district: 3 },
    { key: "wangan", value: "Wangan", district: 3 },
  ],
  marilog: [
    { key: "baganihan", value: "Baganihan", district: 3 },
    { key: "bantul", value: "Bantul", district: 3 },
    { key: "buda", value: "Buda", district: 3 },
    { key: "dalag", value: "Dalag", district: 3 },
    { key: "datu-salumay", value: "Datu Salumay", district: 3 },
    { key: "gumitan", value: "Gumitan", district: 3 },
    { key: "magsaysay", value: "Magsaysay", district: 3 },
    { key: "malamba", value: "Malamba", district: 3 },
    { key: "marilog-proper", value: "Marilog Proper", district: 3 },
    { key: "salaysay", value: "Salaysay", district: 3 },
    { key: "suawan", value: "Suawan (Tuli)", district: 3 },
    { key: "tamugan", value: "Tamugan", district: 3 },
  ],
  toril: [
    { key: "alambre", value: "Alambre", district: 3 },
    { key: "atan-awe", value: "Atan-Awe", district: 3 },
    { key: "bangkas-heights", value: "Bangkas Heights", district: 3 },
    { key: "baracatan", value: "Baracatan", district: 3 },
    { key: "bato", value: "Bato", district: 3 },
    { key: "daliao", value: "Daliao", district: 3 },
    { key: "daliao-plantation", value: "Daliaoan Plantation", district: 3 },
    { key: "eden", value: "Eden", district: 3 },
    { key: "kilate", value: "Kilate", district: 3 },
    { key: "lizada", value: "Lizada", district: 3 },
    { key: "bayabas", value: "Bayabas", district: 3 },
    { key: "binugao", value: "Binugao", district: 3 },
    { key: "camansi", value: "Camansi", district: 3 },
    { key: "mulig", value: "Mulig", district: 3 },
    { key: "catigan", value: "Catigan", district: 3 },
    { key: "crossing-bayabas", value: "Crossing Bayabas", district: 3 },
    { key: "lubogan", value: "Lubogan", district: 3 },
    { key: "marapangi", value: "Marapangi", district: 3 },
    { key: "sibulan", value: "Sibulan", district: 3 },
    { key: "sirawan", value: "Sirawan", district: 3 },
    { key: "tagluno", value: "Tagluno", district: 3 },
    { key: "tagurano", value: "Tagurano", district: 3 },
    { key: "tibuloy", value: "Tibuloy", district: 3 },
    { key: "toril-proper", value: "Toril Proper", district: 3 },
    { key: "tungkalan", value: "Tungkalan", district: 3 },
  ],
  tugbok: [
    { key: "angalan", value: "Angalan", district: 3 },
    { key: "bago-oshiro", value: "Bago Oshiro", district: 3 },
    { key: "balenggaeng", value: "Balenggaeng", district: 3 },
    { key: "biao-escuela", value: "Biao Escuela", district: 3 },
    { key: "biao-guinga", value: "Biao Guinga", district: 3 },
    { key: "los-amigos", value: "Los Amigos", district: 3 },
    { key: "manambulan", value: "Manambulan", district: 3 },
    { key: "manuel-gianga", value: "Manuel Guianga", district: 3 },
    { key: "matina-biao", value: "Matina Biao", district: 3 },
    { key: "mintal", value: "Mintal", district: 3 },
    { key: "new-carmen", value: "New Carmen", district: 3 },
    { key: "new-valencia", value: "New Valencia", district: 3 },
    { key: "sto-niño", value: "Santo Niño", district: 3 },
    { key: "tacunan", value: "Tacunan", district: 3 },
    { key: "tagakpan", value: "Tagakpan", district: 3 },
    { key: "talandang", value: "Talandang", district: 3 },
    { key: "tugbok-proper", value: "Tugbok Proper", district: 3 },
    { key: "ula", value: "Ula", district: 3 },
  ],
};
